### ISSUE TITLE
Updated stock files do not function properly when placed on device.

### ISSUE THREAD

**Issue by Cobaltlantern** [tinkeringtech/scoutmakes#1]
I opened the code.py file and attempted to update the list of preset stations. This resulted in a device that would not boot.

A download and extract from the examples results in an error trying to boot:

"code.py output:
Traceback (most recent call last):
  File "code.py", line 7, in <module>
ImportError: no module named 'adafruit_bus_device'

Code done running."

I can get past this by manually downloading and installing an 'adafruit_bus_device' file to the lib folder, but then it errors on the next one (and so on).

Is there a chance that a folder got dropped from this repository that could be causing this?

**Comment by tinkeringtech** [comment]
Hi there, Please replace the files on your Bluetooth device with the attached.
[fm radio.zip](https://github.com/tinkeringtech/scoutmakes/files/8008846/fm.radio.zip)

**Comment by Cobaltlantern** [comment]
(Thanks for taking a look so fast!)

I replaced the files and ended up with:

"code.py output:
Traceback (most recent call last):
  File "code.py", line 72, in <module>
  File "/lib/tinkeringtech_rda5807m.py", line 184, in __init__
  File "/lib/tinkeringtech_rda5807m.py", line 198, in setup
  File "/lib/tinkeringtech_rda5807m.py", line 439, in saveRegister
  File "/lib/tinkeringtech_rda5807m.py", line 443, in writeBytes
  File "/lib/tinkeringtech_rda5807m.py", line 443, in writeBytes
  File "adafruit_bus_device/i2c_device.py", line 102, in write
OSError: [Errno 19] Unsupported operation

Code done running."

**Comment by tinkeringtech** [comment]
Was the device working prior to the preset changes? Soldering and connections all ok?

**Comment by Cobaltlantern** [comment]
It was functioning as expected after initial setup. I opened the code.py file in Mu editor to adjust the station presets, to a total of 3, saved, and had it return an error.

Not having saved the list of station presets to go back to, I reinstalled from this repo, then it then started this behavior on disconnecting and turning it back on. Returns the errors, and the LED is blinking a sequence.

**Comment by tinkeringtech** [comment]
Could you post the code.py file that gave you the error the first time? Also, to confirm, you overwrote all the library files along with code.py with what I posted earlier?

**Comment by Cobaltlantern** [comment]
I made a huge oversight by overwriting the initial code.py so I do not have the exact code for it.

The only difference in the code was this section:
presets = [  # Preset stations
    8910,
    9070,
    10650
]

And the error returned mentioned i_sidx was unexpected but I assumed it was because there was code referencing presets beyond the 3 I left in.

I hope I'm not causing the issue by doing this wrong, but I deleted all the files from the device via windows explorer, and then extracted the files you provided to the drive. (That said I'm very new at soldering so I wouldn't be surprised if it was a bad connection somewhere.)

**Comment by tinkeringtech** [comment]
the i_sidx value has to be 0,1 0r 2 in your  setup. 
File "code.py", line 72, in
File "/lib/tinkeringtech_rda5807m.py", line 184, in init

The line 72 code was due to the i_sidx being out of range.

Keep at least 7 frequency entries in the presets list since elsewhere in the code, it expects preset 6 on a button press. Does this work?

presets = [  # Preset stations
    8910,
    9070,
    10650
]
i_sidx = 1  # Starting at station with index 1

**Comment by Cobaltlantern** [comment]
The current error I get with unmodified stock files you sent over is this:

code.py output:
Traceback (most recent call last):
  File "code.py", line 72, in <module>
  File "/lib/tinkeringtech_rda5807m.py", line 184, in __init__
  File "/lib/tinkeringtech_rda5807m.py", line 198, in setup
  File "/lib/tinkeringtech_rda5807m.py", line 439, in saveRegister
  File "/lib/tinkeringtech_rda5807m.py", line 443, in writeBytes
  File "/lib/tinkeringtech_rda5807m.py", line 443, in writeBytes
  File "adafruit_bus_device/i2c_device.py", line 102, in write
OSError: [Errno 19] Unsupported operation

There's a chance I've done something in all of this to wiggle a connector or solder join out of place so I can start there and see about reseating things or trying an alternate board/kit.

**Comment by tinkeringtech** [comment]
Yea, please ensure your SDA and SCL pins especially are soldered correctly. Also no solder bridges on the pins. Sorry you are having trouble with this :(

**Comment by Cobaltlantern** [comment]
It's a learning experience! Thank you for looking into it for a new person like me.

(I wanted to also let you know that I reheated and added a little extra solder to both the SDA and SCL pins and it now functions as expected. I'm so sorry I had you running around software-side for a bad solder join.)

**Comment by tinkeringtech** [comment]
Ah, yay!!! I'm so happy you got it to work. Glad I could help. The kits are a learning tool and I'm so glad you are trying it out and debugged it all by yourself. Bravo 😊 🙏 thank you for using our kit!!!
